[build-system]
requires = ["setuptools", "wheel", "setuptools-rust", "colorama", "tqdm", "setuptools_scm[toml]>=6.0"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "bagua-core-py/version.py"
write_to_template = "__version__ = \"{version}\""
