[package]
name = "bagua-core-internal"
version = "0.1.2"
authors = ["Xiangru Lian <admin@mail.xrlian.com>"]
edition = "2018"
publish = ["private"]
build = "build.rs"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
thiserror = "1"
base64 = "0.13"
itertools = "0.10"
shadow-rs = "0.5"
parking_lot = { version = "0.11", features = ["deadlock_detection"] }
hashbrown = "0.11"
lazy_id = "0.1"
flume = "0.10"
oneshot = "0.1"
cpp = "0.5"
sized-object-pool = "0.2"
once_cell = "1.7"
ndarray = "0.15.3"
serde = { version = "1", features = ["derive"] }
scheduled-thread-pool = "0.2"
serde_json = "1.0"
ureq = "2.1"

[dependencies.pyo3]
version = "0.13.2"

[build-dependencies]
shadow-rs = "0.5"
cpp_build = "0.5"
cc = "1.0"
cmd_lib = "1.0"
which = "4.1"
