on: push

name: Cargo check

jobs:
  check:
    runs-on: ubuntu-latest
    container: ikzk/bagua-ci:latest
    steps:
      - uses: actions/checkout@v2
      - name: get-cmake
        uses: lukka/get-cmake@v3.20.1
      - run: rustup default stable
      - run: cargo check
