on: push

name: Cargo check

jobs:
  check:
    runs-on: ubuntu-latest
    container: ikzk/bagua-ci:latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - run: rustup default stable
      - run: pip install .
      - run: cargo check
