on: push

name: check package install

jobs:
  check:
    runs-on: ubuntu-latest
    container: ikzk/bagua-ci:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: rustup default stable
      - run: pip install .
